Repository OvercomingRoom/Bellbell, pull requests merged in 2024-02, with the labels that each got.

#12 [Setting] swagger 설정 추가
  build.gradle
  src/main/java/com/overcomingroom/bellbell/config/SwaggerConfig.java
Labels: ⚙ Setting

#14 [feature] Response, Exception 추가
  src/main/java/com/overcomingroom/bellbell/exception/CustomException.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorResponse.java
  src/main/java/com/overcomingroom/bellbell/exception/GlobalExceptionHandler.java
  src/main/java/com/overcomingroom/bellbell/response/ResResult.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
Labels: ✨ Feature

#15 [Feature] 카카오 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/overcomingroom/bellbell/config/.keep
  src/main/java/com/overcomingroom/bellbell/config/CorsConfig.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/member/controller/.keep
  src/main/java/com/overcomingroom/bellbell/member/domain/dto/.keep
  src/main/java/com/overcomingroom/bellbell/member/domain/dto/KakaoUserInfo.java
  src/main/java/com/overcomingroom/bellbell/member/domain/entity/.keep
  src/main/java/com/overcomingroom/bellbell/member/domain/entity/Member.java
  src/main/java/com/overcomingroom/bellbell/member/domain/service/MemberService.java
  src/main/java/com/overcomingroom/bellbell/member/repository/.keep
  src/main/java/com/overcomingroom/bellbell/member/repository/MemberRepository.java
  src/main/java/com/overcomingroom/bellbell/member/service/.keep
  src/main/java/com/overcomingroom/bellbell/oauth/controller/OAuthController.java
  src/main/java/com/overcomingroom/bellbell/oauth/service/OAuthService.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/resources/application-secret.yml.template
  src/main/resources/application.properties
Labels: ✨ Feature

#16 [Fix] login api 수정
  src/main/java/com/overcomingroom/bellbell/config/SwaggerConfig.java
  src/main/java/com/overcomingroom/bellbell/exception/CustomException.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorResponse.java
  src/main/java/com/overcomingroom/bellbell/exception/GlobalExceptionHandler.java
  src/main/java/com/overcomingroom/bellbell/member/domain/controller/MemberController.java
  src/main/java/com/overcomingroom/bellbell/member/domain/dto/KakaoUserInfo.java
  src/main/java/com/overcomingroom/bellbell/member/domain/entity/Member.java
  src/main/java/com/overcomingroom/bellbell/member/domain/service/MemberService.java
  src/main/java/com/overcomingroom/bellbell/oauth/controller/OAuthController.java
  src/main/java/com/overcomingroom/bellbell/oauth/dto/ResponseToken.java
  src/main/java/com/overcomingroom/bellbell/oauth/service/OAuthService.java
  src/main/java/com/overcomingroom/bellbell/response/ResResult.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor, ✨ Feature

#18 [Feature] 토큰 redis 관리 및 토큰 갱신 스케줄링 구현
  build.gradle
  src/main/java/com/overcomingroom/bellbell/BellbellApplication.java
  src/main/java/com/overcomingroom/bellbell/config/RedisConfig.java
  src/main/java/com/overcomingroom/bellbell/member/domain/controller/MemberController.java
  src/main/java/com/overcomingroom/bellbell/member/domain/service/MemberService.java
  src/main/java/com/overcomingroom/bellbell/oauth/dto/TokenResponse.java
  src/main/java/com/overcomingroom/bellbell/oauth/repository/RedisRepository.java
  src/main/java/com/overcomingroom/bellbell/oauth/service/OAuthService.java
Labels: ✨ Feature
