Repository OvercomingRoom/Bellbell, pull requests merged in 2024-03, with the labels that each got.

#21 [Fix] Swagger Authentication 방식으로 변경
  src/main/java/com/overcomingroom/bellbell/config/SwaggerConfig.java
  src/main/java/com/overcomingroom/bellbell/member/domain/controller/MemberController.java
Labels: 🐞 BugFix

#20 [feature] weather api 호출
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/member/domain/controller/MemberController.java
  src/main/java/com/overcomingroom/bellbell/member/repository/MemberRepository.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/java/com/overcomingroom/bellbell/weather/controller/WeatherController.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/CategoryType.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/FcstDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/FcstItems.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/LocationDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherResponse.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/entity/Location.java
  src/main/java/com/overcomingroom/bellbell/weather/repository/LocationRepository.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: ✨ Feature

#25 [feature] 날씨, 옷차림 정보를 반환합니다.
  src/main/java/com/overcomingroom/bellbell/weather/controller/WeatherController.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/CategoryType.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/LocationDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherAndClothesDto.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: ✨ Feature

#26 [Feature] 사용자 생성 알림 기능 구현
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/member/domain/entity/Member.java
  src/main/java/com/overcomingroom/bellbell/member/domain/service/MemberService.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/java/com/overcomingroom/bellbell/usernotification/controller/UserNotificationController.java
  src/main/java/com/overcomingroom/bellbell/usernotification/domain/dto/UserNotificationRequestDto.java
  src/main/java/com/overcomingroom/bellbell/usernotification/domain/dto/UserNotificationResponseDto.java
  src/main/java/com/overcomingroom/bellbell/usernotification/domain/entity/UserNotification.java
  src/main/java/com/overcomingroom/bellbell/usernotification/repository/UserNotificationRepository.java
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
  src/main/resources/application.yml
Labels: 📬 API, ✨ Feature

#28 [Feature] 동적 스케줄링 기능 추가
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
Labels: ✨ Feature

#29 [Feature] 주소의 경도와 위도로 x y좌표 변환 후 위치 저장
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/member/domain/controller/MemberController.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/java/com/overcomingroom/bellbell/weather/controller/WeatherController.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/GpsTransfer.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherAndClothesDto.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: 🐞 BugFix, ✨ Feature

#31 [fix] 스케줄링 작업을 위한 메서드 매개변수 변경
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
Labels: 🐞 BugFix

#34 [Refactor] entity 재정의
  src/main/java/com/overcomingroom/bellbell/basicNotification/domain/dto/BasicNotificationRequestDto.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/domain/entity/BasicNotification.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/repository/BasicNotificationRepository.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/service/BasicNotificationService.java
  src/main/java/com/overcomingroom/bellbell/weather/controller/WeatherController.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/LocationDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/entity/Location.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/entity/Weather.java
  src/main/java/com/overcomingroom/bellbell/weather/repository/LocationRepository.java
  src/main/java/com/overcomingroom/bellbell/weather/repository/WeatherRepository.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: 🔨 Refactor

#37 [Feature] 날씨 및 옷차림 알림 api 구현
  src/main/java/com/overcomingroom/bellbell/basicNotification/domain/dto/AbstractBasicNotificationDto.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/domain/dto/BasicNotificationRequestDto.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/domain/entity/BasicNotification.java
  src/main/java/com/overcomingroom/bellbell/basicNotification/service/BasicNotificationService.java
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/oauth/service/OAuthService.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/java/com/overcomingroom/bellbell/weather/controller/WeatherController.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherInfoDto.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/entity/Weather.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: 📬 API, ✨ Feature
