Repository OvercomingRoom/Bellbell, pull requests merged in 2024-04, with the labels that each got.

#41 [Refactor] 기본 알림, 사용자 알림 스케줄링 코드 수정
  src/main/java/com/overcomingroom/bellbell/basicNotification/service/BasicNotificationService.java
  src/main/java/com/overcomingroom/bellbell/schedule/CronExpression.java
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: 🔨 Refactor

#44 [Feature] 카카오톡 메시지 보내기
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/kakaoMessage/controller/KakaoMessageTestController.java
  src/main/java/com/overcomingroom/bellbell/kakaoMessage/domain/KakaoMessageDto.java
  src/main/java/com/overcomingroom/bellbell/kakaoMessage/service/CustomMessageService.java
  src/main/java/com/overcomingroom/bellbell/kakaoMessage/service/HttpCallService.java
  src/main/java/com/overcomingroom/bellbell/kakaoMessage/service/KaKaoMessageService.java
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: ✨ Feature

#46 [Feature] 점심 메뉴 랜덤 추천 기능 구현
  csv/menu.csv
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/lunch/controller/LunchController.java
  src/main/java/com/overcomingroom/bellbell/lunch/domain/dto/LunchRequestDto.java
  src/main/java/com/overcomingroom/bellbell/lunch/domain/dto/LunchResponseDto.java
  src/main/java/com/overcomingroom/bellbell/lunch/domain/entity/Lunch.java
  src/main/java/com/overcomingroom/bellbell/lunch/domain/entity/Menu.java
  src/main/java/com/overcomingroom/bellbell/lunch/repository/LunchRepository.java
  src/main/java/com/overcomingroom/bellbell/lunch/repository/MenuRepository.java
  src/main/java/com/overcomingroom/bellbell/lunch/service/LunchService.java
  src/main/java/com/overcomingroom/bellbell/lunch/service/MenuService.java
  src/main/java/com/overcomingroom/bellbell/oauth/service/OAuthService.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
Labels: ✨ Feature

#47 [Feature] 택배 알림 기능 구현
  src/main/java/com/overcomingroom/bellbell/exception/ErrorCode.java
  src/main/java/com/overcomingroom/bellbell/lunch/controller/LunchController.java
  src/main/java/com/overcomingroom/bellbell/lunch/service/LunchService.java
  src/main/java/com/overcomingroom/bellbell/member/domain/entity/Member.java
  src/main/java/com/overcomingroom/bellbell/parcel/controller/ParcelController.java
  src/main/java/com/overcomingroom/bellbell/parcel/domain/dto/ParcelRequestDto.java
  src/main/java/com/overcomingroom/bellbell/parcel/domain/dto/ParcelResponseDto.java
  src/main/java/com/overcomingroom/bellbell/parcel/domain/dto/TrackingInfoDto.java
  src/main/java/com/overcomingroom/bellbell/parcel/domain/entity/Parcel.java
  src/main/java/com/overcomingroom/bellbell/parcel/domain/entity/TrackingInfo.java
  src/main/java/com/overcomingroom/bellbell/parcel/repository/ParcelRepository.java
  src/main/java/com/overcomingroom/bellbell/parcel/repository/TrackingInfoRepository.java
  src/main/java/com/overcomingroom/bellbell/parcel/service/ParcelService.java
  src/main/java/com/overcomingroom/bellbell/response/ResponseCode.java
  src/main/java/com/overcomingroom/bellbell/schedule/ScheduleType.java
  src/main/java/com/overcomingroom/bellbell/usernotification/domain/dto/UserNotificationRequestDto.java
  src/main/java/com/overcomingroom/bellbell/usernotification/service/UserNotificationService.java
  src/main/java/com/overcomingroom/bellbell/weather/domain/dto/WeatherAndClothesDto.java
  src/main/java/com/overcomingroom/bellbell/weather/service/WeatherService.java
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#50 [Release] Bellbell:0.1.0
  Dockerfile
  build.gradle
  src/main/java/com/overcomingroom/bellbell/config/CorsConfig.java
  src/main/java/com/overcomingroom/bellbell/lunch/service/MenuService.java
  src/main/resources/application.yml
  src/main/resources/csv/menu.csv
  src/main/resources/schema.sql
Labels: 🌏 Deploy
